### ISSUE TITLE
Can't set drawing Fill/Stroke color via color picker

### ISSUE THREAD

**Issue by fnzr** [operation404/boneyard-drawing-tools#3]
Using Foundry v10, when trying to set the drawing color via the color picker, and exception shows up on the log and the color is not changed. The error occurs after I click "Select" on the color picker.

On Firefox, the message is: "Uncaught TypeError: can't access property "value", document.querySelector(...) is null
[Detected 1 package: boneyard-drawing-tools]".
This comes from the function 
```
color_dropper_handler(e) {
        document.querySelector("#by-color-selector > div #by-color-text").value = e.target.value;
        this.update_default_colors(e.target.value);
    }
```
The problem here is that (apparently) `#by-color-selector` is null.

Typing the hex color in the text box ("#00FF00" or whatever) correctly changes color.

On Chrome, I get no message and cant change the color either way.

Any idea if I'm doing something wrong?

**Comment by fnzr** [comment]
Commenting out the selection on firefox works:
```
color_dropper_handler(e) {
  //document.querySelector("#by-color-selector > div #by-color-dropper").value = e.target.value;
 this.update_default_colors(e.target.value);
}
```
no dice on chrome, though.

**Comment by operation404** [comment]
Hm, from a quick test I'm unable to replicate the error on chrome, but I'll install Firefox and see if I can replicate it there. When you were testing was this module the only one enabled, or were there any other modules enabled as well? And what specific Foundry build are you on?

**Comment by operation404** [comment]
Alright, I was able to replicate the bug on Firefox and believe I had an idea as to it's cause. It seems to be due to the browser's default color selector. My module doesn't have a built in color selector, it uses whatever the browser provides by default. Additionally, the color editor pane provided by this module is set up to hide itself when the user defocuses the window. It seems like some browser color selectors will open a separate window from the color editor instead of a sub-window, causing the color editor window to hide itself and no longer be referenceable within the document.

I'll start with figuring out how to replicate this issue on Chrome and look into solutions from there. Thank you for bringing this to my attention.

**Comment by fnzr** [comment]
Oh I got it.
The issue with chrome is completely unrelated. On my settings, the "Line width" option was blank

![2023-06-03-16:55:13-screenshot](https://github.com/operation404/boneyard-drawing-tools/assets/5471818/a5cb5873-832d-49cf-87ce-0b9350e700f8)

If it's blank, the chosen color is ignored and it defaults to white. Write a valid value there (a number), and the color picker works correctly on chrome.
