### ISSUE TITLE
Buttons in Quick Draw Config don't work.

### ISSUE THREAD

**Issue by danielbrown96** [operation404/boneyard-drawing-tools#4]
When clicking any button in the config pop up, the pop up just closes to no effect. This includes the line and fill buttons, the colour buttons and the eyedropper button. Clicking in the colour gradient section works fine.

My console displays the following error when the config pop up opens 
![image](https://github.com/operation404/boneyard-drawing-tools/assets/62200149/eeca44ee-1221-45d6-94da-ddfaca15ac02)

I'm using Chrome on Foundry 10.291 and module version 2.0.5

**Comment by operation404** [comment]
Hm, I am unable to replicate this issue on the same Foundry and module versions.

The error in your console is one I've seen in testing before, it should be due to having one of the DragonFlagon modules installed, I believe specifically the DF Module Buttons library module. But the error shouldn't actually prevent anything from working, the button added to the toolbar from this module just doesn't have the same format as the buttons added through that library, so the control manager throws errors when treating it like it does. It's possible an update to them has changed this, but I haven't had issues with them before.

Please try running with just the Drawing Tools module enabled and see if the error persists. If it does, it may be something browser specific, which I can look into. I develop and play Chrome, but it's possible something I've done may not work as expected in Firefox, Opera, or Edge.

If the module does work when it's enabled alone, there's module conflict. I'd need to know what module(s) are causing the issue, but I can see if the conflict is something that can be reasonably resolved and push out a patch if so.

**Comment by danielbrown96** [comment]
Hey mate, that console error was actually unrelated, sorry. Looks like it's actually due to the game system. I created a fresh world with Pathfinder 2nd Edition v4.11.2 (which is what I play in) and it still didn't work, no errors in the console. Then I tried with a fresh world with DnD5e v2.2.1 and it worked as expected. I tried with a handful of other systems I had installed and PF2e was the only one that didn't work.

**Comment by operation404** [comment]
Ah, the pf2e system is quite a complex system, it wouldn't surprise me if there was some complicated code causing problems under the hood. I'll see if I can figure out what may be the problem, I've never used the system before though so it may take me a bit to figure out what's causing it. Thanks for narrowing down the source of the problem.

**Comment by operation404** [comment]
A temporary fix has been released for the pf2e system that should allow this module to be mostly functional again. There are still some problems I haven't figured out yet, so it's not perfect. Notably, clicking on a button and then off the panel won't close the panel. But at the very least the config panel won't just close when clicking on any button at all. A temporary workaround is that if clicking off the panel doesn't close it, click on any blank section of the panel and then click off of it again - that should close it.

**Comment by operation404** [comment]
With release 2.0.7, I believe a sufficient fix has been implemented for this issue that should restore full module functionality while used alongside the pf2e system.

**Comment by danielbrown96** [comment]
Legend
